### ISSUE TITLE
Documentation tracker

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#160]
- [x] #168 Minimal documentation infrastructure
- [ ] #539
- [ ] API docs
  - [ ] Create API docs (https://github.com/IntelPython/numba-dppy/issues/133)
      - [x] #388
      - [ ] #399
  - [ ] #398
- [ ] Docs in CI
  - [ ] Automate docs generation
  - [ ] Upload to GitHub Pages via CI
  - [ ] Lint docstrings
  - [ ] Consider warnings as errors
- [ ] Convert docs from [`numba_dppy/__init__.py`](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/__init__.py) to docs page
  - [ ] Update `Intrinsic Functions` text as it is related to OpenCL (now SYCL is used)
https://github.com/IntelPython/numba-dppy/blob/bafd6548cc4816d412d3007089f42cf550b2c36e/numba_dppy/__init__.py#L69 
  - [ ] Update offloading example as `parallel={'offload':True}` is not supported
https://github.com/IntelPython/numba-dppy/blob/bafd6548cc4816d412d3007089f42cf550b2c36e/numba_dppy/__init__.py#L230
  - [ ] Update the list of supported NumPy functions
https://github.com/IntelPython/numba-dppy/blob/bafd6548cc4816d412d3007089f42cf550b2c36e/numba_dppy/__init__.py#L255
- [ ] Create a list of supported NumPy functions via [dpNP](https://github.com/IntelPython/dpnp) (see #31)
- [ ] Make links to corresponding [examples](https://github.com/IntelPython/numba-dppy/tree/main/numba_dppy/examples) from docs
- [ ] Create docs for features corresponding to `numba.cuda` (from https://github.com/IntelPython/numba-dppy/issues/145)
- [ ] #314
- [ ] #683

Docs sources to convert:
- [ ] [`numba_dppy/__init__.py`](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/__init__.py)
- [ ] [HowTo.rst](https://github.com/IntelPython/numba-dppy/blob/main/HowTo.rst)
   - [ ] Update document as it is based on OpenCL and MS 138
   - [ ] Section [Reduction](https://github.com/IntelPython/numba-dppy/blob/main/HowTo.rst#reduction) does not contain example code.
- [ ] https://github.com/IntelPython/numba-dppy/blob/main/DEBUGGING.md
- [ ] https://github.com/IntelPython/numba-dppy/blob/main/docs/INDEX.md
- [ ] https://github.com/IntelPython/numba-dppy/blob/main/CONTRIBUTING.md

**Comment by diptorupd** [comment]
The ticket is too old to be relevant. I will create a new umbrella ticket for documentation improvement.
