### ISSUE TITLE
Public CI tracker

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#490]
- [x] #507 
- [x] Integration with nightly builds
  - [x] Use dpctl nightly builds #510
  - [x] Use DPNP nightly builds #513 
- [ ] Matrix: numba, numpy, dpctl, dpnp, Linux/Windows/macOS
  - [x] python IntelPython/dpctl#518, IntelPython/numba-dppy#510
- [ ] Packages conda and PyPI (environments, secrets)
  - [x] Build package as artifact and use in CI IntelPython/dpctl#515
  - [x] Build and upload package to public package repository on default branch IntelPython/dpctl#515
  - [x] Build and upload package on release
- [ ] Badge (from GitHub Actions)
- [x] #311
- [x] #439
- [x] Coverage (coveralls, see dpctl) #293  
- [x] #547
- [ ] #526
- [x] DevCloud GPU IntelPython/dpctl#518
- [ ] Benchmarking IntelPython/dpbench#14
- [ ] Integration with gold/2021
- [ ] Use https://github.com/actions/stale for old issues and PRs

Reusable:
- [ ] Action for configuring oneAPI
  - [ ] With cache
- [ ] Workflow reuse (for what projects?)

Bugs:
- [x] #504

Others:
- [ ] Try alternative runners for self-hosted: https://jonico.github.io/awesome-runners/

**Comment by diptorupd** [comment]
Most of these are done. We will close more topical issues as an when needed.
