### ISSUE TITLE
Release 0.20

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#873]
TODO before our 0.20 release

- [x] Complete updating examples [#804]
- [x] Add a case to handle [n,m] kernel launch args in old way. [#804]
- [x] Merge #825 (SDL)
- [x] Merge Khaled's dppy_func changes (if completed)
- [x] Update changelog
- [ ] Update docs (use SM's changes as much as possible)
- [x] Merge [804]
- [x] Skip broken examples
- [x] Fix 2D indexing (blocker) (#871)
- [x] Fix coverage CI
- [x] Fix public windows CI
- [x] dpjit decorator
- [x] boxing unboxing support for dpnp.ndarray in dpjit
- [x] dpnp empty support inside dpjit
- [ ] Modify all dpnp overloads to support CFD
- [x] parfor support for dpnp arrays
- [ ] reduction support for dpnp ndarray

**Comment by diptorupd** [comment]
release is out.
